import { Department } from "@/types";

export const departments: Department[] = [
  {
    id: "materials-mechanical",
    name: "Materials & Mechanical Engineering",
    shortName: "Materials & Mech",
    description:
      "Study stress, materials, manufacturing processes, CAD, FEA simulation, and mechanical design.",
    icon: "⚙️",
    color: "text-orange-700",
    bgColor: "bg-orange-50 border-orange-200",
    questions: [
      { id: 1, text: "Are you ready to calculate stresses and dimension mechanical parts?" },
      { id: 2, text: "Are you ready to study strain, deformation, and material behavior?" },
      { id: 3, text: "Are you ready to study phase diagrams and heat treatments?" },
      { id: 4, text: "Are you ready to choose manufacturing processes (machining, casting)?" },
      { id: 5, text: "Are you ready to analyze tensile and hardness test results?" },
      { id: 6, text: "Are you ready to identify defects like cracks, porosity, and residual stresses?" },
      { id: 7, text: "Are you ready to design mechanical components using CAD?" },
      { id: 8, text: "Are you ready to simulate mechanical systems (FEA)?" },
      { id: 9, text: "Are you ready to understand fatigue and failure of materials?" },
      { id: 10, text: "Are you ready to link microstructure to mechanical properties?" },
    ],
  },
  {
    id: "civil",
    name: "Civil Engineering",
    shortName: "Civil Eng",
    description:
      "Design buildings, bridges, analyze soil mechanics, structural loads, and manage construction projects.",
    icon: "🏗️",
    color: "text-yellow-700",
    bgColor: "bg-yellow-50 border-yellow-200",
    questions: [
      { id: 1, text: "Are you ready to calculate loads on structures?" },
      { id: 2, text: "Are you ready to study soil mechanics?" },
      { id: 3, text: "Are you ready to design buildings and bridges?" },
      { id: 4, text: "Are you ready to read and create construction plans?" },
      { id: 5, text: "Are you ready to analyze concrete and steel behavior?" },
      { id: 6, text: "Are you ready to study fluid flow in pipes and drainage systems?" },
      { id: 7, text: "Are you ready to manage construction sites?" },
      { id: 8, text: "Are you ready to ensure safety and regulations in construction?" },
      { id: 9, text: "Are you ready to use CAD for structural design?" },
      { id: 10, text: "Are you ready to estimate cost and time of construction projects?" },
    ],
  },
  {
    id: "industrial",
    name: "Industrial Engineering",
    shortName: "Industrial Eng",
    description:
      "Optimize production systems, design factory layouts, manage inventory, and coordinate departments.",
    icon: "🏭",
    color: "text-green-700",
    bgColor: "bg-green-50 border-green-200",
    questions: [
      { id: 1, text: "Are you ready to analyze material flow in a factory?" },
      { id: 2, text: "Are you ready to find root causes of production problems?" },
      { id: 3, text: "Are you ready to optimize production systems?" },
      { id: 4, text: "Are you ready to reduce production costs?" },
      { id: 5, text: "Are you ready to design factory layouts?" },
      { id: 6, text: "Are you ready to improve production efficiency?" },
      { id: 7, text: "Are you ready to plan and schedule production?" },
      { id: 8, text: "Are you ready to manage inventory and logistics?" },
      { id: 9, text: "Are you ready to analyze system performance using data?" },
      { id: 10, text: "Are you ready to coordinate between different departments?" },
    ],
  },
  {
    id: "lean",
    name: "Lean / Operational Excellence",
    shortName: "Lean & OpEx",
    description:
      "Apply Lean, Six Sigma, root cause analysis, KPIs, and lead continuous improvement projects.",
    icon: "📊",
    color: "text-teal-700",
    bgColor: "bg-teal-50 border-teal-200",
    questions: [
      { id: 1, text: "Are you ready to map processes and find bottlenecks?" },
      { id: 2, text: "Are you ready to reduce waste in processes?" },
      { id: 3, text: "Are you ready to use Lean and Six Sigma methods?" },
      { id: 4, text: "Are you ready to apply root cause analysis (5 Whys)?" },
      { id: 5, text: "Are you ready to use KPIs and dashboards?" },
      { id: 6, text: "Are you ready to improve processes continuously?" },
      { id: 7, text: "Are you ready to standardize work procedures?" },
      { id: 8, text: "Are you ready to reduce cycle time in operations?" },
      { id: 9, text: "Are you ready to improve quality and reduce defects?" },
      { id: 10, text: "Are you ready to lead improvement projects?" },
    ],
  },
  {
    id: "iot-industry40",
    name: "Electromechanical: Industrial Digitalisation",
    shortName: "Electro Digitalisation",
    description:
      "Design IoT systems, program PLCs, use MATLAB, work with industrial protocols and electronic circuits.",
    icon: "🔌",
    color: "text-blue-700",
    bgColor: "bg-blue-50 border-blue-200",
    questions: [
      { id: 1, text: "Are you ready to design systems with sensors and microcontrollers?" },
      { id: 2, text: "Are you ready to send data to the cloud for analysis?" },
      { id: 3, text: "Are you ready to understand wired and wireless communication?" },
      { id: 4, text: "Are you ready to study industrial communication protocols?" },
      { id: 5, text: "Are you ready to use MATLAB for signal processing?" },
      { id: 6, text: "Are you ready to program PLCs?" },
      { id: 7, text: "Are you ready to understand network protocols and web communication?" },
      { id: 8, text: "Are you ready to design and simulate electronic circuits?" },
      { id: 9, text: "Are you ready to study power electronics and energy conversion?" },
      { id: 10, text: "Are you ready to create dashboards to visualize system data?" },
    ],
  },
  {
    id: "energy",
    name: "Energy Engineering",
    shortName: "Energy Eng",
    description:
      "Study energy generation, renewable systems, electrical machines, power electronics and efficiency.",
    icon: "⚡",
    color: "text-amber-700",
    bgColor: "bg-amber-50 border-amber-200",
    questions: [
      { id: 1, text: "Are you ready to understand energy generation systems?" },
      { id: 2, text: "Are you ready to study energy conversion?" },
      { id: 3, text: "Are you ready to analyze power systems?" },
      { id: 4, text: "Are you ready to calculate efficiency and losses?" },
      { id: 5, text: "Are you ready to study renewable energy systems?" },
      { id: 6, text: "Are you ready to work with power electronics?" },
      { id: 7, text: "Are you ready to study electrical machines (motors, generators)?" },
      { id: 8, text: "Are you ready to analyze energy consumption?" },
      { id: 9, text: "Are you ready to optimize energy efficiency?" },
      { id: 10, text: "Are you ready to simulate energy systems?" },
    ],
  },
  {
    id: "it",
    name: "IT Engineering",
    shortName: "IT Eng",
    description:
      "Develop software, work with databases, networks, cybersecurity basics, and version control tools.",
    icon: "💻",
    color: "text-indigo-700",
    bgColor: "bg-indigo-50 border-indigo-200",
    questions: [
      { id: 1, text: "Are you ready to learn programming languages?" },
      { id: 2, text: "Are you ready to understand data structures?" },
      { id: 3, text: "Are you ready to develop software applications?" },
      { id: 4, text: "Are you ready to study computer networks?" },
      { id: 5, text: "Are you ready to work with databases?" },
      { id: 6, text: "Are you ready to debug and solve code problems?" },
      { id: 7, text: "Are you ready to understand operating systems?" },
      { id: 8, text: "Are you ready to design software architecture?" },
      { id: 9, text: "Are you ready to learn cybersecurity basics?" },
      { id: 10, text: "Are you ready to work with version control tools (Git)?" },
    ],
  },
  {
    id: "ai",
    name: "AI Engineering",
    shortName: "AI Eng",
    description:
      "Study machine learning, deep learning, Python, datasets, model training, computer vision and NLP.",
    icon: "🤖",
    color: "text-purple-700",
    bgColor: "bg-purple-50 border-purple-200",
    questions: [
      { id: 1, text: "Are you ready to study mathematics (linear algebra, probability)?" },
      { id: 2, text: "Are you ready to program in Python?" },
      { id: 3, text: "Are you ready to understand machine learning models?" },
      { id: 4, text: "Are you ready to work with datasets?" },
      { id: 5, text: "Are you ready to train and evaluate models?" },
      { id: 6, text: "Are you ready to improve model performance?" },
      { id: 7, text: "Are you ready to study deep learning?" },
      { id: 8, text: "Are you ready to work on computer vision or NLP?" },
      { id: 9, text: "Are you ready to optimize algorithms?" },
      { id: 10, text: "Are you ready to follow new AI technologies continuously?" },
    ],
  },
  {
    id: "electro-maintenance",
    name: "Electromechanical Engineering: Industrial Maintenance & Control",
    shortName: "Electro Maintenance",
    description:
      "Diagnose machine breakdowns, repair equipment, program PLCs, work with SCADA, and perform preventive maintenance.",
    icon: "🔧",
    color: "text-rose-700",
    bgColor: "bg-rose-50 border-rose-200",
    questions: [
      { id: 1, text: "Are you ready to diagnose breakdowns in industrial machines?" },
      { id: 2, text: "Are you ready to repair electrical and mechanical equipment?" },
      { id: 3, text: "Are you ready to study hydraulic and pneumatic systems?" },
      { id: 4, text: "Are you ready to analyze faults in automated production lines?" },
      { id: 5, text: "Are you ready to program PLCs and control industrial systems?" },
      { id: 6, text: "Are you ready to understand sensors and industrial instrumentation?" },
      { id: 7, text: "Are you ready to monitor systems using SCADA and control interfaces?" },
      { id: 8, text: "Are you ready to perform preventive and predictive maintenance?" },
      { id: 9, text: "Are you ready to improve machine reliability and reduce downtime?" },
      { id: 10, text: "Are you ready to work in a real industrial environment (factory, site)?" },
    ],
  },
  {
    id: "mechanical-structures",
    name: "Mechanical Engineering: Structures",
    shortName: "Mech Structures",
    description:
      "Calculate stresses, analyze structures under load, design with CAD, simulate with FEA, and verify safety of designs.",
    icon: "🏛️",
    color: "text-gray-700",
    bgColor: "bg-gray-50 border-gray-200",
    questions: [
      { id: 1, text: "Are you ready to calculate stresses and dimension mechanical parts?" },
      { id: 2, text: "Are you ready to study deformation and material behavior?" },
      { id: 3, text: "Are you ready to analyze structures under different loads?" },
      { id: 4, text: "Are you ready to design mechanical systems using CAD software?" },
      { id: 5, text: "Are you ready to simulate structures using FEA tools?" },
      { id: 6, text: "Are you ready to study fatigue and failure of materials?" },
      { id: 7, text: "Are you ready to understand thermodynamics and energy systems?" },
      { id: 8, text: "Are you ready to choose materials based on mechanical properties?" },
      { id: 9, text: "Are you ready to verify the safety and reliability of designs?" },
      { id: 10, text: "Are you ready to work in design offices or engineering projects?" },
    ],
  },
];
